<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_5dfbd8c7345f4',
	'title' => 'Banner',
	'fields' => array(
		array(
			'key' => 'field_5dfbd8d71f0cc',
			'label' => 'Imagem do banner',
			'name' => 'slide_img',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 1020,
			'min_height' => 420,
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => 2,
			'mime_types' => 'JPG, PNG',
		),
		array(
			'key' => 'field_5dfbd9471f0cd',
			'label' => 'Área',
			'name' => 'area',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'descubra' => 'Descubra Itabirito',
				'programacao' => 'Programação',
				'noticias' => 'Notícias',
				'negocios' => 'Padrão',
				'servicos' => 'Serviços',
				'prefeitura' => 'A Prefeitura',
				'servidor' => 'Espaço do servidor',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_669ff931158a0',
			'label' => 'Link',
			'name' => 'pagelink',
			'aria-label' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'post_type' => '',
			'post_status' => '',
			'taxonomy' => '',
			'allow_archives' => 1,
			'multiple' => 0,
			'allow_null' => 0,
		),
		array(
			'key' => 'field_5dfbdbed14268',
			'label' => 'URL',
			'name' => 'slide_url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_669ff931158a0',
						'operator' => '==empty',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'banner',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_54f4d5b3a3a2b',
	'title' => 'Contas Públicas',
	'fields' => array(
		array(
			'key' => 'field_54f4c645c2561',
			'label' => 'Ano',
			'name' => 'ano',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 4,
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_54f4c64ec2562',
			'label' => 'Mês',
			'name' => 'mes',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'formatting' => 'html',
			'maxlength' => 2,
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_54f4c659c2563',
			'label' => 'Arquivo (PDF)',
			'name' => 'arquivo',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'library' => 'all',
			'return_format' => 'array',
			'min_size' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array(
			'key' => 'field_5501cd58b05c5',
			'label' => 'Data',
			'name' => 'data',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Inserir mês e ano para o documento.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '2015-04',
			'prepend' => '',
			'append' => '',
			'maxlength' => 7,
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'conta',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5fa19db807c48',
	'title' => 'Contatos Secretaria/Conselho',
	'fields' => array(
		array(
			'key' => 'field_5fa19e1ca9e08',
			'label' => 'Contato',
			'name' => 'contato',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Adicionar contato',
			'sub_fields' => array(
				array(
					'key' => 'field_5fa19e4da9e09',
					'label' => 'Local',
					'name' => 'local',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'popup',
						3 => 'popup_theme',
						4 => 'noticia',
						5 => 'convenio',
						6 => 'procuradoria',
						7 => 'glossario',
						8 => 'plano',
						9 => 'conta',
						10 => 'controle',
						11 => 'licitacao',
						12 => 'programacao',
						13 => 'banner',
						14 => 'conselho',
						15 => 'secretaria',
						16 => 'selecao',
						17 => 'agencia',
						18 => 'restaurante',
						19 => 'hospedagem',
						20 => 'atracao',
						21 => 'ponto-turistico',
						22 => 'roteiro',
						23 => 'diferencial',
						24 => 'telefone-util',
						25 => 'escola',
						26 => 'associacao',
						27 => 'unidade-saude',
						28 => 'cooperativa',
						29 => 'oficio',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'modalidades-contas',
						4 => 'tipos-contas',
						5 => 'modalidades-licitacao',
						6 => 'tipos',
						7 => 'modalidade_procuradoria',
						8 => 'tipo_procuradoria',
						9 => 'categoria_programacao',
						10 => 'categoria',
						11 => 'tipo_selecao',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5fa19e1ca9e08',
				),
				array(
					'key' => 'field_5fa19e5ca9e0a',
					'label' => 'Telefone',
					'name' => 'telefone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'popup',
						3 => 'popup_theme',
						4 => 'noticia',
						5 => 'convenio',
						6 => 'procuradoria',
						7 => 'glossario',
						8 => 'plano',
						9 => 'conta',
						10 => 'controle',
						11 => 'licitacao',
						12 => 'programacao',
						13 => 'banner',
						14 => 'conselho',
						15 => 'secretaria',
						16 => 'selecao',
						17 => 'agencia',
						18 => 'restaurante',
						19 => 'hospedagem',
						20 => 'atracao',
						21 => 'ponto-turistico',
						22 => 'roteiro',
						23 => 'diferencial',
						24 => 'telefone-util',
						25 => 'escola',
						26 => 'associacao',
						27 => 'unidade-saude',
						28 => 'cooperativa',
						29 => 'oficio',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'modalidades-contas',
						4 => 'tipos-contas',
						5 => 'modalidades-licitacao',
						6 => 'tipos',
						7 => 'modalidade_procuradoria',
						8 => 'tipo_procuradoria',
						9 => 'categoria_programacao',
						10 => 'categoria',
						11 => 'tipo_selecao',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5fa19e1ca9e08',
				),
				array(
					'key' => 'field_5fa19e87a9e0b',
					'label' => 'Endereço',
					'name' => 'endereco',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'popup',
						3 => 'popup_theme',
						4 => 'noticia',
						5 => 'convenio',
						6 => 'procuradoria',
						7 => 'glossario',
						8 => 'plano',
						9 => 'conta',
						10 => 'controle',
						11 => 'licitacao',
						12 => 'programacao',
						13 => 'banner',
						14 => 'conselho',
						15 => 'secretaria',
						16 => 'selecao',
						17 => 'agencia',
						18 => 'restaurante',
						19 => 'hospedagem',
						20 => 'atracao',
						21 => 'ponto-turistico',
						22 => 'roteiro',
						23 => 'diferencial',
						24 => 'telefone-util',
						25 => 'escola',
						26 => 'associacao',
						27 => 'unidade-saude',
						28 => 'cooperativa',
						29 => 'oficio',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'modalidades-contas',
						4 => 'tipos-contas',
						5 => 'modalidades-licitacao',
						6 => 'tipos',
						7 => 'modalidade_procuradoria',
						8 => 'tipo_procuradoria',
						9 => 'categoria_programacao',
						10 => 'categoria',
						11 => 'tipo_selecao',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5fa19e1ca9e08',
				),
				array(
					'key' => 'field_5fa19e90a9e0c',
					'label' => 'Horário de funcionamento',
					'name' => 'horario_de_funcionamento',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'popup',
						3 => 'popup_theme',
						4 => 'noticia',
						5 => 'convenio',
						6 => 'procuradoria',
						7 => 'glossario',
						8 => 'plano',
						9 => 'conta',
						10 => 'controle',
						11 => 'licitacao',
						12 => 'programacao',
						13 => 'banner',
						14 => 'conselho',
						15 => 'secretaria',
						16 => 'selecao',
						17 => 'agencia',
						18 => 'restaurante',
						19 => 'hospedagem',
						20 => 'atracao',
						21 => 'ponto-turistico',
						22 => 'roteiro',
						23 => 'diferencial',
						24 => 'telefone-util',
						25 => 'escola',
						26 => 'associacao',
						27 => 'unidade-saude',
						28 => 'cooperativa',
						29 => 'oficio',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'modalidades-contas',
						4 => 'tipos-contas',
						5 => 'modalidades-licitacao',
						6 => 'tipos',
						7 => 'modalidade_procuradoria',
						8 => 'tipo_procuradoria',
						9 => 'categoria_programacao',
						10 => 'categoria',
						11 => 'tipo_selecao',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5fa19e1ca9e08',
				),
			),
			'rows_per_page' => 20,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'secretaria',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'conselho',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_560e893de9989',
	'title' => 'Controles',
	'fields' => array(
		array(
			'key' => 'field_560e89f5957aa',
			'label' => 'Arquivos',
			'name' => 'arquivos',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Adicionar Linha',
			'sub_fields' => array(
				array(
					'key' => 'field_560e8a0e957ab',
					'label' => 'Título',
					'name' => 'titulo',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
					'parent_repeater' => 'field_560e89f5957aa',
				),
				array(
					'key' => 'field_560e8a14957ac',
					'label' => 'PDF',
					'name' => 'pdf',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'parent_repeater' => 'field_560e89f5957aa',
				),
				array(
					'key' => 'field_5953d86dfa628',
					'label' => 'Ano',
					'name' => 'ano',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => 'Ano da publicação',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => 1000,
					'max' => 3000,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
					'parent_repeater' => 'field_560e89f5957aa',
				),
			),
			'rows_per_page' => 20,
			'collapsed' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'control',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5f08bfbc709c6',
	'title' => 'Dados de contato',
	'fields' => array(
		array(
			'key' => 'field_5f08bfdc249e6',
			'label' => 'Endereço',
			'name' => 'endereco',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f08c007249e7',
			'label' => 'Telefone',
			'name' => 'telefone',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f08c020249e8',
			'label' => 'Horário de funcionamento',
			'name' => 'horario_de_funcionamento',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5f08c03f249e9',
			'label' => 'Facebook',
			'name' => 'facebook',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5f08c070249ea',
			'label' => 'E-mail',
			'name' => 'e-mail',
			'aria-label' => '',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5f08c083249eb',
			'label' => 'Website',
			'name' => 'url',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'restaurante',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'hospedagem',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'agencia',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'telefone-util',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'associacao',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'unidade-saude',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'escola',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'associacao',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cooperativa',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5ec4062bac792',
	'title' => 'Decretos COVID',
	'fields' => array(
		array(
			'key' => 'field_5ec406438d235',
			'label' => 'Decretos e portarias',
			'name' => 'decreto',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Adicionar linha',
			'sub_fields' => array(
				array(
					'key' => 'field_5ec406658d236',
					'label' => 'Arquivo do decreto',
					'name' => 'decreto-arquivo',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'parent_repeater' => 'field_5ec406438d235',
				),
			),
			'rows_per_page' => 20,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '33222',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_54f5f26e62cf8',
	'title' => 'Em destaque?',
	'fields' => array(
		array(
			'key' => 'field_5df7cb24eabd0',
			'label' => 'Em destaque na página principal?',
			'name' => 'destaque',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Marque esta opção se a notícia deve ir para a área de destaques.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'noticia',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'programacao',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_55b670c329a34',
	'title' => 'Informações',
	'fields' => array(
		array(
			'key' => 'field_55b670c88ce6f',
			'label' => 'Telefone',
			'name' => 'telefone',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55b670e48ce70',
			'label' => 'Endereço',
			'name' => 'endereco',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55b670fc8ce71',
			'label' => 'Horário',
			'name' => 'horario',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55b78b13882e6',
			'label' => 'Email',
			'name' => 'email',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_parent',
				'operator' => '==',
				'value' => '1653',
			),
		),
		array(
			array(
				'param' => 'page_parent',
				'operator' => '==',
				'value' => '2028',
			),
		),
		array(
			array(
				'param' => 'page',
				'operator' => '==',
				'value' => '1778',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_55008d81d2ac2',
	'title' => 'Licitações e contratos',
	'fields' => array(
		array(
			'key' => 'field_55008d81e1721',
			'label' => 'Ano',
			'name' => 'ano',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 4,
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_55008d81e181c',
			'label' => 'Arquivo (PDF)',
			'name' => 'arquivo',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'licitacao',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'convenio',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'procuradoria',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5f3d9050ca4f0',
	'title' => 'Links relacionados',
	'fields' => array(
		array(
			'key' => 'field_5fa2d876d2580',
			'label' => 'Links relacionadas',
			'name' => 'links_relacionadas',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Adicionar linha',
			'sub_fields' => array(
				array(
					'key' => 'field_5fa41ef49ec1e',
					'label' => 'Nome do site',
					'name' => 'url_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => array(
						0 => 'post',
						1 => 'page',
						2 => 'popup',
						3 => 'popup_theme',
						4 => 'noticia',
						5 => 'convenio',
						6 => 'procuradoria',
						7 => 'glossario',
						8 => 'plano',
						9 => 'conta',
						10 => 'controle',
						11 => 'licitacao',
						12 => 'programacao',
						13 => 'banner',
						14 => 'conselho',
						15 => 'secretaria',
						16 => 'selecao',
						17 => 'agencia',
						18 => 'restaurante',
						19 => 'hospedagem',
						20 => 'atracao',
						21 => 'ponto-turistico',
						22 => 'roteiro',
						23 => 'diferencial',
						24 => 'telefone-util',
						25 => 'escola',
						26 => 'associacao',
						27 => 'unidade-saude',
						28 => 'cooperativa',
						29 => 'oficio',
					),
					'admin_column_taxonomies' => array(
						0 => 'category',
						1 => 'post_tag',
						2 => 'link_category',
						3 => 'modalidades-contas',
						4 => 'tipos-contas',
						5 => 'modalidades-licitacao',
						6 => 'tipos',
						7 => 'modalidade_procuradoria',
						8 => 'tipo_procuradoria',
						9 => 'categoria_programacao',
						10 => 'categoria',
						11 => 'tipo_selecao',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'parent_repeater' => 'field_5fa2d876d2580',
				),
				array(
					'key' => 'field_5fa2d98bd2584',
					'label' => 'Link externo relacionado',
					'name' => 'url_relacionado',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5fa41eb79ec1d',
								'operator' => '==',
								'value' => 'url',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'admin_column_post_types' => '',
					'admin_column_taxonomies' => '',
					'default_value' => '',
					'placeholder' => '',
					'parent_repeater' => 'field_5fa2d876d2580',
				),
			),
			'rows_per_page' => 20,
		),
		array(
			'key' => 'field_5fa2d90cd2581',
			'label' => 'Páginas',
			'name' => 'paginas_relacionadas',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5fa41eb79ec1d',
						'operator' => '==',
						'value' => 'page',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'post_type' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'noticia',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'secretaria',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'conselho',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_661007b0d0a13',
	'title' => 'Página de secretaria',
	'fields' => array(
		array(
			'key' => 'field_661007b1acc28',
			'label' => 'É conteúdo de secretaria',
			'name' => 'conteudo_secretaria',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_661007e4acc29',
			'label' => 'Qual?',
			'name' => 'nome_secretaria',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_661007b1acc28',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'post_type' => array(
				0 => 'secretaria',
			),
			'post_status' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
			),
			'return_format' => 'id',
			'min' => '',
			'max' => '',
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'conselho',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'oficio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_54f5f6b483bda',
	'title' => 'Programações',
	'fields' => array(
		array(
			'key' => 'field_54f5f7f32ea82',
			'label' => 'Cabeçalho da página',
			'name' => 'banner',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_54f5f6bd804f7',
			'label' => 'Datas',
			'name' => 'datas',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Datas do evento',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Adicionar Linha',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_54f5f6de2ea7d',
					'label' => 'Data Inicial',
					'name' => 'data_inicial',
					'aria-label' => '',
					'type' => 'date_time_picker',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'display_format' => 'Y-m-d H:i:s',
					'return_format' => 'Y-m-d H:i:s',
					'first_day' => 1,
					'parent_repeater' => 'field_54f5f6bd804f7',
				),
				array(
					'key' => 'field_54f5f7072ea7e',
					'label' => 'Data única?',
					'name' => 'data_unica',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'parent_repeater' => 'field_54f5f6bd804f7',
				),
				array(
					'key' => 'field_54f5f7452ea7f',
					'label' => 'Data Final',
					'name' => 'data_final',
					'aria-label' => '',
					'type' => 'date_time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_54f5f7072ea7e',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'admin_column_enabled' => 0,
					'display_format' => 'Y-m-d H:i:s',
					'return_format' => 'Y-m-d H:i:s',
					'first_day' => 1,
					'parent_repeater' => 'field_54f5f6bd804f7',
				),
			),
		),
		array(
			'key' => 'field_66a9077c89e3e',
			'label' => 'Evento virtual',
			'name' => 'evento_virtual',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_66a8fe2d734b9',
			'label' => 'Local do evento',
			'name' => 'local_do_evento',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66a9077c89e3e',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'choices' => array(
				'casadecultura' => 'Casa de Cultura Maestro Dungas',
				'centenario' => 'Praça do Centenário',
				'estacao' => 'Complexo da Estação',
				'inconfidentes' => 'Praça dos Inconfidentes (Área do Julifest)',
				'xavier' => 'Centro Cultural Padre Francisco Xavier',
				'ecologico' => 'Parque Ecológico Municipal',
				'agroparque' => 'Parque Agropecuário Tarciso Bretas Lima',
				'skate' => 'Pista de Skate',
				'pump' => 'Pista de Pump Track (Padre Adelmo)',
				'imigrantes' => 'Praça dos Imigrantes',
				'sebastiao' => 'Praça São Sebastião',
				'mercado' => 'Mercado Municipal de Itabirito',
				'outro' => 'Outro',
			),
			'default_value' => false,
			'return_format' => 'array',
			'multiple' => 0,
			'allow_null' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_66a90096734ba',
			'label' => 'Local do evento',
			'name' => 'outro_local',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66a8fe2d734b9',
						'operator' => '==',
						'value' => 'outro',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66a9083c93b65',
			'label' => 'Endereço virtual do evento',
			'name' => 'endereco_virtual',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => 'Preencha com o endereço do evento virtual ou transmissão online do evento.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_54f5f7712ea80',
			'label' => 'É anual',
			'name' => 'anual',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5dfd183a217cd',
			'label' => 'Destaque',
			'name' => 'destaque',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_66a9421f4a721',
			'label' => 'Formulário de inscrição',
			'name' => 'formulario_de_inscricao',
			'aria-label' => '',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'post_type' => array(
				0 => 'page',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'allow_archives' => 0,
			'multiple' => 0,
			'allow_null' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'programacao',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_59d6765525cf6',
	'title' => 'Revisão de Plano Diretor',
	'fields' => array(
		array(
			'key' => 'field_59d676642332b',
			'label' => 'PDF',
			'name' => 'pdf',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'plano',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6685bbc8bc317',
	'title' => 'Secretaria-mãe',
	'fields' => array(
		array(
			'key' => 'field_6685bbc965e6e',
			'label' => 'Secretaria-mãe',
			'name' => 'parent_secretaria',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'post_type' => array(
				0 => 'secretaria',
			),
			'post_status' => '',
			'taxonomy' => '',
			'filters' => '',
			'return_format' => 'id',
			'min' => '',
			'max' => '',
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'secretaria',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5fa2da711d9fd',
	'title' => 'Secretário',
	'fields' => array(
		array(
			'key' => 'field_5fa2da88ce8f3',
			'label' => 'Secretário',
			'name' => 'secretario',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => array(
				0 => 'post',
				1 => 'page',
				2 => 'popup',
				3 => 'popup_theme',
				4 => 'noticia',
				5 => 'convenio',
				6 => 'procuradoria',
				7 => 'glossario',
				8 => 'plano',
				9 => 'conta',
				10 => 'controle',
				11 => 'licitacao',
				12 => 'programacao',
				13 => 'banner',
				14 => 'conselho',
				15 => 'secretaria',
				16 => 'selecao',
				17 => 'agencia',
				18 => 'restaurante',
				19 => 'hospedagem',
				20 => 'atracao',
				21 => 'ponto-turistico',
				22 => 'roteiro',
				23 => 'diferencial',
				24 => 'telefone-util',
				25 => 'escola',
				26 => 'associacao',
				27 => 'unidade-saude',
				28 => 'cooperativa',
				29 => 'oficio',
			),
			'admin_column_taxonomies' => array(
				0 => 'category',
				1 => 'post_tag',
				2 => 'link_category',
				3 => 'modalidades-contas',
				4 => 'tipos-contas',
				5 => 'modalidades-licitacao',
				6 => 'tipos',
				7 => 'modalidade_procuradoria',
				8 => 'tipo_procuradoria',
				9 => 'categoria_programacao',
				10 => 'categoria',
				11 => 'tipo_selecao',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'secretaria',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_560ec2c718b74',
	'title' => 'Serviços disponíveis',
	'fields' => array(
		array(
			'key' => 'field_560ec3329758d',
			'label' => 'Arquivos',
			'name' => 'arquivos',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Adicionar',
			'sub_fields' => array(
				array(
					'key' => 'field_560ec36832d97',
					'label' => 'Título',
					'name' => 'titulo',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
					'parent_repeater' => 'field_560ec3329758d',
				),
				array(
					'key' => 'field_560ec2c72e6d3',
					'label' => 'Arquivo (PDF)',
					'name' => 'arquivo',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'parent_repeater' => 'field_560ec3329758d',
				),
			),
			'rows_per_page' => 20,
			'collapsed' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_parent',
				'operator' => '==',
				'value' => '2157',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5f45455e0a459',
	'title' => 'Tipo de cooperativa de transporte',
	'fields' => array(
		array(
			'key' => 'field_5f4545fa904ab',
			'label' => 'Tipo de cooperativa de transporte',
			'name' => 'tipo',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'choices' => array(
				'pontos-de-taxi' => 'Pontos de táxi',
				'particular' => 'Transporte particular (Aluguel de vans e empresas de ônibus)',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'array',
			'save_other_choice' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cooperativa',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_558dd033e76b2',
	'title' => 'Tipos de associações Comunitárias e Entidades',
	'fields' => array(
		array(
			'key' => 'field_5f45360c7f01f',
			'label' => 'Tipo de associação',
			'name' => 'tipo',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 0,
			'admin_column_post_types' => '',
			'admin_column_taxonomies' => '',
			'choices' => array(
				'associacao_comunitaria' => 'Associação comunitária',
				'ong' => 'Organização Não-governamental',
				'entidade' => 'Outras entidades',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'array',
			'save_other_choice' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'associacao',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5f0f5d659c1e7',
	'title' => 'Tipos de hospedagem',
	'fields' => array(
		array(
			'key' => 'field_5f0f5d734e4c8',
			'label' => 'Tipo de hospedagem',
			'name' => 'tipo',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'rural' => 'Rural',
				'urbana' => 'Urbana',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'array',
			'save_other_choice' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'hospedagem',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5f08beb10fe86',
	'title' => 'Tipos de restaurantes',
	'fields' => array(
		array(
			'key' => 'field_5f08bebfdfa9c',
			'label' => 'Tipo de estabelecimento',
			'name' => 'tipo',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'restaurante' => 'Restaurante',
				'bar-cafe' => 'Bar/Café',
				'padaria' => 'Padaria',
				'sorveteria' => 'Sorveteria',
				'lanchonete' => 'Lanchonete',
				'trailer' => 'Trailer',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'array',
			'save_other_choice' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'restaurante',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5f1601437ee6f',
	'title' => 'Tipos de telefones úteis',
	'fields' => array(
		array(
			'key' => 'field_5f16015dbc677',
			'label' => 'Tipo de estabelecimento',
			'name' => 'tipo',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'banco' => 'Agências bancárias',
				'farmacia' => 'Farmácias',
				'utilidade' => 'Utilidade Pública',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'horizontal',
			'return_format' => 'array',
			'save_other_choice' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'telefone-util',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5f40046876538',
	'title' => 'Tipos de unidades educacionais',
	'fields' => array(
		array(
			'key' => 'field_5f400474578ff',
			'label' => 'Tipo de unidade educacional',
			'name' => 'tipo',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'admin_column_enabled' => 1,
			'admin_column_post_types' => array(
				0 => 'escola',
			),
			'admin_column_taxonomies' => '',
			'choices' => array(
				'escola-municipal' => 'Escola municipal',
				'escola-especial' => 'Escola especial',
				'creche-muncipal' => 'Creche municipal',
				'zona-rural' => 'Escola municipal da Zona Rural',
				'federal' => 'Instituição Federal',
				'pre-escola' => 'Pré-escola municipal',
				'estadual' => 'Escola estadual',
				'particular' => 'Escola Particular',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'array',
			'save_other_choice' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'escola',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );

	acf_add_local_field_group( array(
	'key' => 'group_5f3d829de7155',
	'title' => 'Trabalhe conosco / Seleção',
	'fields' => array(
		array(
			'key' => 'field_5f3d82c1e65cc',
			'label' => 'Documentos',
			'name' => 'documentos',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Adicionar linha',
			'sub_fields' => array(
				array(
					'key' => 'field_5f3d82f5e65cd',
					'label' => 'Arquivo',
					'name' => 'arquivo',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'parent_repeater' => 'field_5f3d82c1e65cc',
				),
			),
			'rows_per_page' => 20,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'selecao',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => false,
) );
} );



?>